### ISSUE TITLE
[1.18.2] Rebound "boomerang" crashes world when using sully's mod Jade Flinger Totems

### ISSUE THREAD

**Issue by Shibva** [SammySemicolon/Malum-Mod#168]
A fatal error occurs when the rebound entity its in close proximity to a Jade Flinger Totem from the mod: Sully's Mod

Steps to reproduce:

1, Install Sullys mod for 1.18.2
2. place 4 flinger totems in this configurations (each face faces one side, the faces must form a circle as so)
![image](https://user-images.githubusercontent.com/38770780/218289197-3c94900b-7960-4c8e-8016-862900e500a7.png)

3, throw scythe or item wtih rebound on it

![image](https://user-images.githubusercontent.com/38770780/218289211-4c649b15-e3c1-417a-be30-9e2ae567f141.png)
4. Crash

Crash report:
[crash-2023-02-11_21.13.17-client.txt](https://github.com/SammySemicolon/Malum-Mod/files/10715127/crash-2023-02-11_21.13.17-client.txt)

Overall error summary:
```Time: 2/11/23, 9:13 PM
Description: Saving entity NBT

java.lang.NullPointerException: Cannot invoke "net.minecraft.world.item.ItemStack.serializeNBT()" because "this.scythe" is null
	at com.sammy.malum.common.entity.boomerang.ScytheBoomerangEntity.m_7380_(ScytheBoomerangEntity.java:195) ~[malum-1.18.2-1.4.4.3.jar%23132!/:1.18.2-1.4.4.3] {re:classloading}
	at net.minecraft.world.entity.Entity.m_20240_(Entity.java:1494) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:EntityMixin,pl:mixin:APP:etched.mixins.json:EntityMixin,pl:mixin:APP:relics.mixins.json:MixinEntity,pl:mixin:APP:allurement.mixins.json:EntityMixin,pl:mixin:APP:supplementaries.mixins.json:EntityMixin,pl:mixin:APP:blueprint.mixins.json:EntityMixin,pl:mixin:APP:hexplat.mixins.json:accessor.AccessorEntity,pl:mixin:APP:travelerstitles.mixins.json:EntityChangeDimensionMixin,pl:mixin:APP:pollen-common.mixins.json:EntityMixin,pl:mixin:APP:pollen.mixins.json:EntityMixin,pl:mixin:APP:quark.mixins.json:EntityMixin,pl:mixin:APP:lodestone.mixins.json:EntityMixin,pl:mixin:APP:domesticationinnovation.mixins.json:EntityMixin,pl:mixin:APP:create.mixins.json:ContraptionDriverInteractMixin,pl:mixin:APP:create.mixins.json:EntityContraptionInteractionMixin,pl:mixin:A}
	at com.uraneptus.sullysmod.core.events.SMEntityEvents.onProjectileHitsBlock(SMEntityEvents.java:73) ~[sullysmod-1.1.4-beta.jar%23167!/:1.1.4-beta] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_294_SMEntityEvents_onProjectileHitsBlock_ProjectileImpactEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onProjectileImpact(ForgeEventFactory.java:649) ~[forge-1.18.2-40.1.93-universal.jar%23187!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.entity.projectile.ThrowableProjectile.m_8119_(ThrowableProjectile.java:61) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?] {re:classloading}
	at com.sammy.malum.common.entity.boomerang.ScytheBoomerangEntity.m_8119_(ScytheBoomerangEntity.java:125) ~[malum-1.18.2-1.4.4.3.jar%23132!/:1.18.2-1.4.4.3] {re:classloading}
	at net.minecraft.client.multiplayer.ClientLevel.m_104639_(ClientLevel.java:222) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:rubidium.mixins.json:features.chunk_rendering.MixinClientWorld,pl:mixin:APP:rubidium.mixins.json:features.fast_biome_colors.MixinClientWorld,pl:mixin:APP:dogslie.mixins.json:ClientLevelMixin,pl:mixin:APP:betterbiomeblend.mixins.json:MixinClientWorld,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:blueprint.mixins.json:client.ClientLevelMixin,pl:mixin:APP:hexplat.mixins.json:client.MixinClientLevel,pl:mixin:APP:pollen-common.mixins.json:client.ClientLevelMixin,pl:mixin:APP:flywheel.mixins.json:ClientLevelMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.level.Level.m_46653_(Level.java:487) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:A}
	at net.minecraft.client.multiplayer.ClientLevel.m_194182_(ClientLevel.java:204) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:rubidium.mixins.json:features.chunk_rendering.MixinClientWorld,pl:mixin:APP:rubidium.mixins.json:features.fast_biome_colors.MixinClientWorld,pl:mixin:APP:dogslie.mixins.json:ClientLevelMixin,pl:mixin:APP:betterbiomeblend.mixins.json:MixinClientWorld,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:blueprint.mixins.json:client.ClientLevelMixin,pl:mixin:APP:hexplat.mixins.json:client.MixinClientLevel,pl:mixin:APP:pollen-common.mixins.json:client.ClientLevelMixin,pl:mixin:APP:flywheel.mixins.json:ClientLevelMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?] {re:classloading}
	at net.minecraft.client.multiplayer.ClientLevel.m_104804_(ClientLevel.java:202) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:rubidium.mixins.json:features.chunk_rendering.MixinClientWorld,pl:mixin:APP:rubidium.mixins.json:features.fast_biome_colors.MixinClientWorld,pl:mixin:APP:dogslie.mixins.json:ClientLevelMixin,pl:mixin:APP:betterbiomeblend.mixins.json:MixinClientWorld,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:blueprint.mixins.json:client.ClientLevelMixin,pl:mixin:APP:hexplat.mixins.json:client.MixinClientLevel,pl:mixin:APP:pollen-common.mixins.json:client.ClientLevelMixin,pl:mixin:APP:flywheel.mixins.json:ClientLevelMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1693) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:aileron-common.mixins.json:MinecraftMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:konkrete.mixin.json:client.MixinMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:travelerstitles.mixins.json:MinecraftClientTickMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1021) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:aileron-common.mixins.json:MinecraftMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:konkrete.mixin.json:client.MixinMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:travelerstitles.mixins.json:MinecraftClientTickMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:aileron-common.mixins.json:MinecraftMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:konkrete.mixin.json:client.MixinMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:travelerstitles.mixins.json:MinecraftClientTickMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.93.jar%2317!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.sammy.malum.common.entity.boomerang.ScytheBoomerangEntity.m_7380_(ScytheBoomerangEntity.java:195) ~[malum-1.18.2-1.4.4.3.jar%23132!/:1.18.2-1.4.4.3] {re:classloading}
	at net.minecraft.world.entity.Entity.m_20240_(Entity.java:1494) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:EntityMixin,pl:mixin:APP:etched.mixins.json:EntityMixin,pl:mixin:APP:relics.mixins.json:MixinEntity,pl:mixin:APP:allurement.mixins.json:EntityMixin,pl:mixin:APP:supplementaries.mixins.json:EntityMixin,pl:mixin:APP:blueprint.mixins.json:EntityMixin,pl:mixin:APP:hexplat.mixins.json:accessor.AccessorEntity,pl:mixin:APP:travelerstitles.mixins.json:EntityChangeDimensionMixin,pl:mixin:APP:pollen-common.mixins.json:EntityMixin,pl:mixin:APP:pollen.mixins.json:EntityMixin,pl:mixin:APP:quark.mixins.json:EntityMixin,pl:mixin:APP:lodestone.mixins.json:EntityMixin,pl:mixin:APP:domesticationinnovation.mixins.json:EntityMixin,pl:mixin:APP:create.mixins.json:ContraptionDriverInteractMixin,pl:mixin:APP:create.mixins.json:EntityContraptionInteractionMixin,pl:mixin:A}
	at com.uraneptus.sullysmod.core.events.SMEntityEvents.onProjectileHitsBlock(SMEntityEvents.java:73) ~[sullysmod-1.1.4-beta.jar%23167!/:1.1.4-beta] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_294_SMEntityEvents_onProjectileHitsBlock_ProjectileImpactEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onProjectileImpact(ForgeEventFactory.java:649) ~[forge-1.18.2-40.1.93-universal.jar%23187!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.entity.projectile.ThrowableProjectile.m_8119_(ThrowableProjectile.java:61) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?] {re:classloading}
	at com.sammy.malum.common.entity.boomerang.ScytheBoomerangEntity.m_8119_(ScytheBoomerangEntity.java:125) ~[malum-1.18.2-1.4.4.3.jar%23132!/:1.18.2-1.4.4.3] {re:classloading}
	at net.minecraft.client.multiplayer.ClientLevel.m_104639_(ClientLevel.java:222) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:rubidium.mixins.json:features.chunk_rendering.MixinClientWorld,pl:mixin:APP:rubidium.mixins.json:features.fast_biome_colors.MixinClientWorld,pl:mixin:APP:dogslie.mixins.json:ClientLevelMixin,pl:mixin:APP:betterbiomeblend.mixins.json:MixinClientWorld,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:blueprint.mixins.json:client.ClientLevelMixin,pl:mixin:APP:hexplat.mixins.json:client.MixinClientLevel,pl:mixin:APP:pollen-common.mixins.json:client.ClientLevelMixin,pl:mixin:APP:flywheel.mixins.json:ClientLevelMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.level.Level.m_46653_(Level.java:487) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:A}
	at net.minecraft.client.multiplayer.ClientLevel.m_194182_(ClientLevel.java:204) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:rubidium.mixins.json:features.chunk_rendering.MixinClientWorld,pl:mixin:APP:rubidium.mixins.json:features.fast_biome_colors.MixinClientWorld,pl:mixin:APP:dogslie.mixins.json:ClientLevelMixin,pl:mixin:APP:betterbiomeblend.mixins.json:MixinClientWorld,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:blueprint.mixins.json:client.ClientLevelMixin,pl:mixin:APP:hexplat.mixins.json:client.MixinClientLevel,pl:mixin:APP:pollen-common.mixins.json:client.ClientLevelMixin,pl:mixin:APP:flywheel.mixins.json:ClientLevelMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?] {re:classloading}
	at net.minecraft.client.multiplayer.ClientLevel.m_104804_(ClientLevel.java:202) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:rubidium.mixins.json:features.chunk_rendering.MixinClientWorld,pl:mixin:APP:rubidium.mixins.json:features.fast_biome_colors.MixinClientWorld,pl:mixin:APP:dogslie.mixins.json:ClientLevelMixin,pl:mixin:APP:betterbiomeblend.mixins.json:MixinClientWorld,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:blueprint.mixins.json:client.ClientLevelMixin,pl:mixin:APP:hexplat.mixins.json:client.MixinClientLevel,pl:mixin:APP:pollen-common.mixins.json:client.ClientLevelMixin,pl:mixin:APP:flywheel.mixins.json:ClientLevelMixin,pl:mixin:A,pl:runtimedistcleaner:A}
-- Entity being saved --
Details:
	Entity Type: malum:scythe_boomerang (com.sammy.malum.common.entity.boomerang.ScytheBoomerangEntity)
	Entity ID: 1576
	Entity Name: Scythe Boomerang
	Entity's Exact location: -71.50, 107.50, -230.50
	Entity's Block location: World: (-72,107,-231), Section: (at 8,11,9 in -5,6,-15; chunk contains blocks -80,-64,-240 to -65,319,-225), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Entity's Momentum: 0.00, 0.00, 1.49
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.world.entity.Entity.m_20240_(Entity.java:1494) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:EntityMixin,pl:mixin:APP:etched.mixins.json:EntityMixin,pl:mixin:APP:relics.mixins.json:MixinEntity,pl:mixin:APP:allurement.mixins.json:EntityMixin,pl:mixin:APP:supplementaries.mixins.json:EntityMixin,pl:mixin:APP:blueprint.mixins.json:EntityMixin,pl:mixin:APP:hexplat.mixins.json:accessor.AccessorEntity,pl:mixin:APP:travelerstitles.mixins.json:EntityChangeDimensionMixin,pl:mixin:APP:pollen-common.mixins.json:EntityMixin,pl:mixin:APP:pollen.mixins.json:EntityMixin,pl:mixin:APP:quark.mixins.json:EntityMixin,pl:mixin:APP:lodestone.mixins.json:EntityMixin,pl:mixin:APP:domesticationinnovation.mixins.json:EntityMixin,pl:mixin:APP:create.mixins.json:ContraptionDriverInteractMixin,pl:mixin:APP:create.mixins.json:EntityContraptionInteractionMixin,pl:mixin:A}
	at com.uraneptus.sullysmod.core.events.SMEntityEvents.onProjectileHitsBlock(SMEntityEvents.java:73) ~[sullysmod-1.1.4-beta.jar%23167!/:1.1.4-beta] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_294_SMEntityEvents_onProjectileHitsBlock_ProjectileImpactEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onProjectileImpact(ForgeEventFactory.java:649) ~[forge-1.18.2-40.1.93-universal.jar%23187!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.entity.projectile.ThrowableProjectile.m_8119_(ThrowableProjectile.java:61) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?] {re:classloading}
	at com.sammy.malum.common.entity.boomerang.ScytheBoomerangEntity.m_8119_(ScytheBoomerangEntity.java:125) ~[malum-1.18.2-1.4.4.3.jar%23132!/:1.18.2-1.4.4.3] {re:classloading}
	at net.minecraft.client.multiplayer.ClientLevel.m_104639_(ClientLevel.java:222) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:rubidium.mixins.json:features.chunk_rendering.MixinClientWorld,pl:mixin:APP:rubidium.mixins.json:features.fast_biome_colors.MixinClientWorld,pl:mixin:APP:dogslie.mixins.json:ClientLevelMixin,pl:mixin:APP:betterbiomeblend.mixins.json:MixinClientWorld,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:blueprint.mixins.json:client.ClientLevelMixin,pl:mixin:APP:hexplat.mixins.json:client.MixinClientLevel,pl:mixin:APP:pollen-common.mixins.json:client.ClientLevelMixin,pl:mixin:APP:flywheel.mixins.json:ClientLevelMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.level.Level.m_46653_(Level.java:487) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:A}
	at net.minecraft.client.multiplayer.ClientLevel.m_194182_(ClientLevel.java:204) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:rubidium.mixins.json:features.chunk_rendering.MixinClientWorld,pl:mixin:APP:rubidium.mixins.json:features.fast_biome_colors.MixinClientWorld,pl:mixin:APP:dogslie.mixins.json:ClientLevelMixin,pl:mixin:APP:betterbiomeblend.mixins.json:MixinClientWorld,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:blueprint.mixins.json:client.ClientLevelMixin,pl:mixin:APP:hexplat.mixins.json:client.MixinClientLevel,pl:mixin:APP:pollen-common.mixins.json:client.ClientLevelMixin,pl:mixin:APP:flywheel.mixins.json:ClientLevelMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?] {re:classloading}
	at net.minecraft.client.multiplayer.ClientLevel.m_104804_(ClientLevel.java:202) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:rubidium.mixins.json:features.chunk_rendering.MixinClientWorld,pl:mixin:APP:rubidium.mixins.json:features.fast_biome_colors.MixinClientWorld,pl:mixin:APP:dogslie.mixins.json:ClientLevelMixin,pl:mixin:APP:betterbiomeblend.mixins.json:MixinClientWorld,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:blueprint.mixins.json:client.ClientLevelMixin,pl:mixin:APP:hexplat.mixins.json:client.MixinClientLevel,pl:mixin:APP:pollen-common.mixins.json:client.ClientLevelMixin,pl:mixin:APP:flywheel.mixins.json:ClientLevelMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1693) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:aileron-common.mixins.json:MinecraftMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:konkrete.mixin.json:client.MixinMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:travelerstitles.mixins.json:MinecraftClientTickMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1021) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:aileron-common.mixins.json:MinecraftMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:konkrete.mixin.json:client.MixinMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:travelerstitles.mixins.json:MinecraftClientTickMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:aileron-common.mixins.json:MinecraftMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:konkrete.mixin.json:client.MixinMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:travelerstitles.mixins.json:MinecraftClientTickMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.93.jar%2317!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
```

**Comment by Shibva** [comment]
Note; I was unsure where to report this considering the situation

**Comment by SammySemicolon** [comment]
I believe it's a problem with Malum? though I'm not really sure why.

**Comment by SammySemicolon** [comment]
Fixed as of 
https://maven.blamejared.com/com/sammy/malum/malum/1.18.2-1.5-14/
