### ISSUE TITLE
Placebo - [Malum Log] Forge 1.19.2

### ISSUE THREAD

**Issue by Krimatoria** [SammySemicolon/Malum-Mod#230]
Forge 43.3.5
Placebo-1.19.2-7.3.5.jar 

I don't have this mod, but Minecraft gives these errors in red in the log.
[The answer of the Placebo developer about this problem.](https://github.com/Shadows-of-Fire/Placebo/issues/77)
However, there was a slightly different log than now.

[00:19:23] [Render thread/ERROR]: Codec failure for type Affix Loot Entry, message: Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: malum:crude_scythe
[00:19:23] [Render thread/ERROR]: Failed parsing affix_loot_entries file apotheotic_additions:overworld/crude_scythe.
[00:19:23] [Render thread/ERROR]: Underlying Exception: 
java.lang.RuntimeException: Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: malum:crude_scythe
	at com.mojang.serialization.DataResult.lambda$getOrThrow$4(DataResult.java:100) ~[datafixerupper-5.0.28.jar%23126!/:?]
	at com.mojang.datafixers.util.Either$Right.map(Either.java:99) ~[datafixerupper-5.0.28.jar%23126!/:?]
	at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:93) ~[datafixerupper-5.0.28.jar%23126!/:?]
	at shadows.placebo.json.PSerializer.lambda$fromCodec$2(PSerializer.java:122) ~[Placebo-1.19.2-7.3.5.jar%23639!/:7.3.5]
	at shadows.placebo.json.PSerializer.read(PSerializer.java:76) ~[Placebo-1.19.2-7.3.5.jar%23639!/:7.3.5]
	at shadows.placebo.json.PlaceboJsonReloadListener.lambda$apply$0(PlaceboJsonReloadListener.java:99) ~[Placebo-1.19.2-7.3.5.jar%23639!/:7.3.5]
	at java.util.HashMap.forEach(Unknown Source) ~[?:?]
	at shadows.placebo.json.PlaceboJsonReloadListener.apply(PlaceboJsonReloadListener.java:91) ~[Placebo-1.19.2-7.3.5.jar%23639!/:7.3.5]
	at shadows.placebo.json.PlaceboJsonReloadListener.m_5787_(PlaceboJsonReloadListener.java:47) ~[Placebo-1.19.2-7.3.5.jar%23639!/:7.3.5]
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.Minecraft.m_18701_(Minecraft.java:5919) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_233096_(WorldOpenFlows.java:130) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_233122_(WorldOpenFlows.java:109) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.doLoadLevel(WorldOpenFlows.java:148) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_233145_(WorldOpenFlows.java:136) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_233133_(WorldOpenFlows.java:58) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldSelectionList$WorldListEntry.m_101744_(WorldSelectionList.java:586) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldSelectionList$WorldListEntry.m_101704_(WorldSelectionList.java:448) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldSelectionList$WorldListEntry.m_6375_(WorldSelectionList.java:375) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.gui.components.AbstractSelectionList.m_6375_(AbstractSelectionList.java:336) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_6375_(ContainerEventHandler.java:27) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:88) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:522) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:85) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81) ~[lwjgl-glfw-3.3.1.jar%23144!/:build 7]
	at bre2el.fpsreducer.handler.glfw.InputEventHandler$MouseButtonEventHandler.invoke(InputEventHandler.java:133) ~[FpsReducer2-forge-1.19.2-2.1.jar%23552!/:1.19.2-2.1]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar%23144!/:build 7]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%23136!/:build 7]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar%23144!/:build 7]
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:204) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:337) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1143) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.3.5.jar%23101!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
[00:19:23] [Render thread/ERROR]: Codec failure for type Affix Loot Entry, message: Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: malum:soul_stained_steel_scythe
[00:19:23] [Render thread/ERROR]: Failed parsing affix_loot_entries file apotheotic_additions:overworld/soul_stained_steel_scythe.
[00:19:23] [Render thread/ERROR]: Underlying Exception: 
java.lang.RuntimeException: Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: malum:soul_stained_steel_scythe
	at com.mojang.serialization.DataResult.lambda$getOrThrow$4(DataResult.java:100) ~[datafixerupper-5.0.28.jar%23126!/:?]
	at com.mojang.datafixers.util.Either$Right.map(Either.java:99) ~[datafixerupper-5.0.28.jar%23126!/:?]
	at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:93) ~[datafixerupper-5.0.28.jar%23126!/:?]
	at shadows.placebo.json.PSerializer.lambda$fromCodec$2(PSerializer.java:122) ~[Placebo-1.19.2-7.3.5.jar%23639!/:7.3.5]
	at shadows.placebo.json.PSerializer.read(PSerializer.java:76) ~[Placebo-1.19.2-7.3.5.jar%23639!/:7.3.5]
	at shadows.placebo.json.PlaceboJsonReloadListener.lambda$apply$0(PlaceboJsonReloadListener.java:99) ~[Placebo-1.19.2-7.3.5.jar%23639!/:7.3.5]
	at java.util.HashMap.forEach(Unknown Source) ~[?:?]
	at shadows.placebo.json.PlaceboJsonReloadListener.apply(PlaceboJsonReloadListener.java:91) ~[Placebo-1.19.2-7.3.5.jar%23639!/:7.3.5]
	at shadows.placebo.json.PlaceboJsonReloadListener.m_5787_(PlaceboJsonReloadListener.java:47) ~[Placebo-1.19.2-7.3.5.jar%23639!/:7.3.5]
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.Minecraft.m_18701_(Minecraft.java:5919) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_233096_(WorldOpenFlows.java:130) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_233122_(WorldOpenFlows.java:109) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.doLoadLevel(WorldOpenFlows.java:148) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_233145_(WorldOpenFlows.java:136) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_233133_(WorldOpenFlows.java:58) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldSelectionList$WorldListEntry.m_101744_(WorldSelectionList.java:586) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldSelectionList$WorldListEntry.m_101704_(WorldSelectionList.java:448) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldSelectionList$WorldListEntry.m_6375_(WorldSelectionList.java:375) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.gui.components.AbstractSelectionList.m_6375_(AbstractSelectionList.java:336) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_6375_(ContainerEventHandler.java:27) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:88) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:522) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:85) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81) ~[lwjgl-glfw-3.3.1.jar%23144!/:build 7]
	at bre2el.fpsreducer.handler.glfw.InputEventHandler$MouseButtonEventHandler.invoke(InputEventHandler.java:133) ~[FpsReducer2-forge-1.19.2-2.1.jar%23552!/:1.19.2-2.1]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar%23144!/:build 7]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%23136!/:build 7]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar%23144!/:build 7]
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:204) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:337) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1143) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23723!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.3.5.jar%23101!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]

**Comment by DeUloO** [comment]
Is Placebo your full modlist, or are there any other mods? I don't think this is a malum issue as the error stems from Affix registration which is Placebo and not Malum => As the people over on your Placebo issue said: Do you have any datapacks installed that use Malum? And as Shadows of Fire said: "This is a user error" so neither Sammy nor Shadows of Fire can fix this - check your datapacks/addons of whatever modpack/mod configuration you are playing?
(I am not a dev on malum so I might be wrong about this)
![sof](https://github.com/SammySemicolon/Malum-Mod/assets/99496313/50014d7b-4d1a-4b62-b38f-1279b2f239d3)

**Comment by Krimatoria** [comment]
> Placebo — это ваш полный список модов или есть еще какие-нибудь моды? Я не думаю, что это проблема Malum, поскольку ошибка связана с регистрацией Affix, который является Placebo, а не Malum => Как сказали люди, обсуждавшие вашу проблему с Placebo: установлены ли у вас какие-либо пакеты данных, использующие Malum? И, как сказали в Shadows of Fire: «Это ошибка пользователя», поэтому ни Сэмми, ни Shadows of Fire не могут это исправить — проверьте свои пакеты данных/аддоны той конфигурации модпака/мода, в которую вы играете? (Я не разработчик малума, поэтому могу ошибаться) ![мягкий](https://private-user-images.githubusercontent.com/99496313/303949231-50014d7b-4d1a-4b62-b38f-1279b2f239d3.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2ODg1NjMsIm5iZiI6MTcwNzY4ODI2MywicGF0aCI6Ii85OTQ5NjMxMy8zMDM5NDkyMzEtNTAwMTRkN2ItNGQxYS00YjYyLWIzOGYtMTI3OWIyZjIzOWQzLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDIxNTEwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzNDVlMWNhYjRlM2IxODc3NGZjNWI0NTkwNzdjYzUzNTMzYmQ1NzcxNDRiZWExODJhZjc5YjNkYzI0Y2Q4ZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NMxknid2mp3XMANonl97q4LLEi0-IvvhTd8zkAhmIBY)

Thank you for the answer) the truth has not become clearer yet) Yes, I have a FearNightfall build that I have added with other mods, now there are about 280+

If I knew what to look for at least, which mods can cause it, I could test it.

**Comment by Krimatoria** [comment]
I just uploaded the log to ChatGPT. That's what she replied:

![image](https://github.com/SammySemicolon/Malum-Mod/assets/106809386/65d1010e-5212-43a8-bb1d-47a4f8b9ebb7)

**Comment by Krimatoria** [comment]
I created a branch for [Apotheotic Additions](https://github.com/Bryce792/ApotheoticAdditions/issues/13), maybe there will be a solution there.

**Comment by DeUloO** [comment]
I just ran Minecraft (1.19.2) with:
Apotheosis 6.4.1
Apotheotic Additions 1.0.2
Patchouli 77
Placebo 7.3.5
No issues. Again: You have some kind of datapack/mod that tries to add in Malum items, but it doesn't account for it not existing.
Not a Malum issue. From me running it with all those listed mods, without any issues, it's also very likely not an error because of any of the mods, but rather one of the datapacks/configs or similiar you added.

**Comment by Krimatoria** [comment]
> Я только что запустил Minecraft (1.19.2) с: Apotheosis 6.4.1 Apotheotic Additions 1.0.2 Patchouli 77 Placebo 7.3.5 Никаких проблем. Опять же: у вас есть какой-то пакет данных/мод, который пытается добавить предметы в Malum, но он не учитывает их отсутствие. Это не проблема Малума. Если я запустил его со всеми перечисленными модами без каких-либо проблем, то, скорее всего, это не ошибка какого-либо из модов, а скорее один из добавленных вами пакетов данных/конфигураций или аналогичных.

I'll be looking....but tomorrow...

**Comment by Krimatoria** [comment]
> I just ran Minecraft (1.19.2) with: Apotheosis 6.4.1 Apotheotic Additions 1.0.2 Patchouli 77 Placebo 7.3.5 No issues. Again: You have some kind of datapack/mod that tries to add in Malum items, but it doesn't account for it not existing. Not a Malum issue. From me running it with all those listed mods, without any issues, it's also very likely not an error because of any of the mods, but rather one of the datapacks/configs or similiar you added.

Very interesting) I did the same on a clean build) But I already have this error)

**Comment by Krimatoria** [comment]
[12Feb2024 02:16:00.108] [Render thread/ERROR] [Apotheosis : Adventure/]: Use of the "rarity" key in affix loot pool entries is deprecated and will be removed in a future release.
127 | [12Feb2024 02:16:00.108] [Render thread/ERROR] [Apotheosis : Adventure/]: Use of the "rarity" key in affix loot pool entries is deprecated and will be removed in a future release.
128 | [12Feb2024 02:16:00.111] [Render thread/ERROR] [Apotheosis : Adventure/]: Use of the "rarity" key in affix loot pool entries is deprecated and will be removed in a future release.
129 | [12Feb2024 02:16:00.707] [Render thread/INFO] [placebo/]: Registered 31 additional loot tables.
130 | [12Feb2024 02:16:00.820] [Render thread/INFO] [net.minecraft.advancements.AdvancementList/]: Loaded 1233 advancements
131 | [12Feb2024 02:16:00.827] [Render thread/INFO] [placebo/]: Registered 27 additional recipes.
132 | [12Feb2024 02:16:00.852] [Render thread/INFO] [Apotheosis : Enchantment/]: Registered 33 enchanting_stats.
133 | [12Feb2024 02:16:00.872] [Render thread/INFO] [Apotheosis : Adventure/]: Registered 84 affixes.
134 | [12Feb2024 02:16:00.887] [Render thread/INFO] [Apotheosis : Adventure/]: Registered 21 gems.
135 | [12Feb2024 02:16:00.892] [Render thread/ERROR] [placebo/]: Codec failure for type Affix Loot Entry, message: Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: malum:crude_scythe
136 | [12Feb2024 02:16:00.892] [Render thread/ERROR] [Apotheosis : Adventure/]: Failed parsing affix_loot_entries file apotheotic_additions:overworld/crude_scythe.
137 | [12Feb2024 02:16:00.892] [Render thread/ERROR] [Apotheosis : Adventure/]: Underlying Exception:

**Comment by Krimatoria** [comment]
OMG - https://github.com/Shadows-of-Fire/Apotheosis/issues/1154#issuecomment-1934359511
"https://www.curseforge.com/minecraft/mc-mods/apotheotic-additions is shipping invalid content
ask them about it"

**Comment by SammySemicolon** [comment]
1.18.2/1.19.2 is no longer supported
